### ISSUE TITLE
[REQUEST] Other aspects of the UI of Plasma

### ISSUE THREAD

**Issue by hydino2085143** [baduhai/Koi#2]
Being able to change the Global Theme, Widget Style, Cursor Set, and Window Decoration would be nice. I was about to suggest Kvantum too, but that seems to be suggested in #1 already.

**Comment by baduhai** [comment]
> Global Theme

This would be pretty easy to implement, I'm just no entirely sure why people would want this. You can achieve what the Global Theme does with all the themeing capability Koi already has. I won't outright scrap the idea, as there may be a convincing argument for it, but I definitely won't prioritise it.

> Widget Style

This one's doable quite easily as well, though I'm not entirely sure why a user would want to change widget styles depending on the time of the day. In my mind, I want UI consistency; meaning while colours may change, I want the widgets themselves to stay consistent. Again, I'm not gonna outright scrap the idea, but it'll go towards the bottom in terms of priority.

> Cursor Style

A previous unreleased version of Koi had this functionality, but because various different applications are so inconsistent about recognising that a new cursor is being used I dropped support for it. Until I can find a way that makes all applications recognise the new icon theme immediately, I will not consider adding back support for this.

> Window Decoration

This one is a bit tricky, as the setting for changing the window decoration requires multiple fields which aren't always consistent in the location they are stored in. I'll evaluate the feasibility of this, and see whether I'll work on it or not.

Thank you for the suggestions, expect Kvantum support in the coming weeks. :wink:

**Comment by mirthestam** [comment]
> > Global Theme
> 
> This would be pretty easy to implement, I'm just no entirely sure why people would want this. You can achieve what the Global Theme does with all the themeing capability Koi already has. I won't outright scrap the idea, as there may be a convincing argument for it, but I definitely won't prioritise it.

Well, that is what global themes are for. You you can install i.e. `arc` and `arc-dark` from the store. And then, it would be nice to be able to just use Koi to toggle between them. Novice users are probably not interested in the details a theme is composed of.

**Comment by baduhai** [comment]
> Novice users are probably not interested in the details a theme is composed of.

Novice users are also likely not interested in a too such as Koi, and if they are, it's unlikely that they'll find Koi at all, since the project is so small.

**Comment by mirthestam** [comment]
> > Novice users are probably not interested in the details a theme is composed of.
> 
> Novice users are also likely not interested in a tool such as Koi, and if they are, it's unlikely that they'll find Koi at all, since the project is so small.

I am not so sure about that. I would not be surprised if a functionality like Koi would be integrated into Plasma some day. Although probably in simplified form. But If i understand correctly, the targeted users for Koi are for more experienced users. So, let's forget about the novice ones.

Myself, I am a more experienced user. However I still prefer to use global themes. Therefore, I would still like to request this feature. I do not think it conflicts with the other options. You could still apply those, when enabled, after activating a global theme.

**Comment by baduhai** [comment]
> I would not be surprised if a functionality like Koi would be integrated into Plasma some day.

I certainly hope so. With Plasma being so feature-rich it's a wonder why it hasn't been implemented yet.

> I do not think it conflicts with the other options.

It definitely doesn't, as long as the Global Theme is applied before the other options, there should be no clashes. I could add the option fairly easily, but since I personally don't see a need for the feature, I will be prioritizing other features. I'll gladly accept pull requests though :wink:.

**Comment by Da-Viper** [comment]
I have been thinking of this for some time .

to change all the aspects of the ui, however the most efficient way of doing this is using the global theme. 

basically the global theme is in charge of everything concerning the ui ( except gtk application which is no problem since it has already been implemented in koi ), from icon, cursors to splash screens. 

when installed, the global theme creates a default file that chooses the icon theme, widget style, cursors etc 

why to use the global theme ? 

- being able to have consistent cursor, through out the desktop or workspace 

- able to change the window decoration / taskbar 

- being able to switch between kvantum / oxygen ot breeze right from koi 

- able to set kvantum theme for light and breeze for dark indepentently 

- this would make it easier to implement  more than two theme to switch between as you can just give the user all the list of installed global themes or a page to choose all the aspects of the ui to sooth his/her taste 

why not to use global theme ? 

currently koi changes themes by writing into some files and using would make it  deprecated 

it will also massively change the code base to comply with global themes 

the available time of the main developer is main as this may be a side project to him/her and would not want to as he/she has other things to do.


How it would work  

koi would have two global themes one for light  and one for dark 

you just get the name and write it to the defaults file 

create a metadata.desktop file with koi light and koi dark as names 

create a compressed tar file in the /tmp folder  for both light and dark 

install it using kpackagetool5  command that way it shows up in the lookfeeltool --list 

to change theme is just a simple command of lookandfeeltool -a <THEME_NAME> 


by no extent am i proficient in c++ or qt api as i literally started learning it few weeks ago 

this would definitely take some time of my time and be working on it on a different branch ( something like koi-global) 

i am more worried of it never getting accepted to master  

however  everything here is based on the main developer if it thinks it makes sense or it is a good idea 

because i have no plans on making another kde theme switcher application, with a good one like koi being available just to add some minor features

**Comment by baduhai** [comment]
> koi would have two global themes one for light and one for dark

Actually, that's how I began the development of Koi, but ultimately decided against it. This is because the method of writing a global theme file(package? not sure how to call it), can be inconsistent with some aspects of Plasma(for example: Window Decoration). This would mean that it's actually harder for me to use the pre-existing kpackagetool5 program, than to write Koi the way I wrote it.

**Comment by Da-Viper** [comment]
we don't actually have to use the kpackagetool to install a global theme as long as it is in the look and feel folder with the right directory hierarchy and defaults file.  

the way i did it was to have the two defaults file for koi light and dark and write the themes gotten from koirc straight to the global theme defaults file.  

this also includes widow decoration, and it can be set in koirc settings, here is what i mean [HERE ](https://github.com/Da-Viper/Koi/blob/allInOne/src/utils.cpp#L258)  then when switching between light and dark you can use the 
[lookandfeeltool  ](https://github.com/Da-Viper/Koi/blob/allInOne/src/utils.cpp#L306) -a <name of theme > ( either koi light or dark ) .

**Comment by baduhai** [comment]
I'm not interested in implementing any of the features listed in this. Closing.
